/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoluntariadoRouteImport } from './routes/voluntariado'
import { Route as VidaUniversitariaRouteImport } from './routes/vida-universitaria'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as PideOracionRouteImport } from './routes/pide-oracion'
import { Route as OportunidadesRouteImport } from './routes/oportunidades'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OportunidadesVoluntariadoLourdesRouteImport } from './routes/oportunidades_.voluntariado-lourdes'

const VoluntariadoRoute = VoluntariadoRouteImport.update({
  id: '/voluntariado',
  path: '/voluntariado',
  getParentRoute: () => rootRouteImport,
} as any)
const VidaUniversitariaRoute = VidaUniversitariaRouteImport.update({
  id: '/vida-universitaria',
  path: '/vida-universitaria',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const PideOracionRoute = PideOracionRouteImport.update({
  id: '/pide-oracion',
  path: '/pide-oracion',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesRoute = OportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesVoluntariadoLourdesRoute =
  OportunidadesVoluntariadoLourdesRouteImport.update({
    id: '/oportunidades_/voluntariado-lourdes',
    path: '/oportunidades/voluntariado-lourdes',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oportunidades': typeof OportunidadesRoute
  '/pide-oracion': typeof PideOracionRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/vida-universitaria': typeof VidaUniversitariaRoute
  '/voluntariado': typeof VoluntariadoRoute
  '/oportunidades/voluntariado-lourdes': typeof OportunidadesVoluntariadoLourdesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oportunidades': typeof OportunidadesRoute
  '/pide-oracion': typeof PideOracionRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/vida-universitaria': typeof VidaUniversitariaRoute
  '/voluntariado': typeof VoluntariadoRoute
  '/oportunidades/voluntariado-lourdes': typeof OportunidadesVoluntariadoLourdesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oportunidades': typeof OportunidadesRoute
  '/pide-oracion': typeof PideOracionRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/vida-universitaria': typeof VidaUniversitariaRoute
  '/voluntariado': typeof VoluntariadoRoute
  '/oportunidades_/voluntariado-lourdes': typeof OportunidadesVoluntariadoLourdesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/oportunidades'
    | '/pide-oracion'
    | '/sobre-nosotros'
    | '/vida-universitaria'
    | '/voluntariado'
    | '/oportunidades/voluntariado-lourdes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/oportunidades'
    | '/pide-oracion'
    | '/sobre-nosotros'
    | '/vida-universitaria'
    | '/voluntariado'
    | '/oportunidades/voluntariado-lourdes'
  id:
    | '__root__'
    | '/'
    | '/oportunidades'
    | '/pide-oracion'
    | '/sobre-nosotros'
    | '/vida-universitaria'
    | '/voluntariado'
    | '/oportunidades_/voluntariado-lourdes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OportunidadesRoute: typeof OportunidadesRoute
  PideOracionRoute: typeof PideOracionRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  VidaUniversitariaRoute: typeof VidaUniversitariaRoute
  VoluntariadoRoute: typeof VoluntariadoRoute
  OportunidadesVoluntariadoLourdesRoute: typeof OportunidadesVoluntariadoLourdesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voluntariado': {
      id: '/voluntariado'
      path: '/voluntariado'
      fullPath: '/voluntariado'
      preLoaderRoute: typeof VoluntariadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vida-universitaria': {
      id: '/vida-universitaria'
      path: '/vida-universitaria'
      fullPath: '/vida-universitaria'
      preLoaderRoute: typeof VidaUniversitariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pide-oracion': {
      id: '/pide-oracion'
      path: '/pide-oracion'
      fullPath: '/pide-oracion'
      preLoaderRoute: typeof PideOracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades': {
      id: '/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof OportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades_/voluntariado-lourdes': {
      id: '/oportunidades_/voluntariado-lourdes'
      path: '/oportunidades/voluntariado-lourdes'
      fullPath: '/oportunidades/voluntariado-lourdes'
      preLoaderRoute: typeof OportunidadesVoluntariadoLourdesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OportunidadesRoute: OportunidadesRoute,
  PideOracionRoute: PideOracionRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  VidaUniversitariaRoute: VidaUniversitariaRoute,
  VoluntariadoRoute: VoluntariadoRoute,
  OportunidadesVoluntariadoLourdesRoute: OportunidadesVoluntariadoLourdesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
